# Devolverá una lista con todos los registros
GET http://localhost:5000/f_restfull/api/recipes HTTP/1.1

###
# Devolverá un lista esta búsqueda
GET http://localhost:5000/f_restfull/api/recipes?con=vodka HTTP/1.1

###
# Creará un registro nuevo a partir de los parámetros 
# que enviemos con el POST, y devolverá el id del registro creado, y sus datos
POST http://localhost:5000/f_restfull/api/recipes HTTP/1.1
Content-Type: application/json

{
    "name":"Cubatillapara2",
    "ingredients":[{"name":"Coke","quantity":{"unit":"ml","amount":40}}],
    "instructions":["Shake the cup and shout."],
    "slug":"cubatillapara2"
}

###
# Devolver el resgistro correspondiente al id dado
GET http://localhost:5000/f_restfull/api/recipes/5f7b4b6204799f5cf837b1e1 HTTP/1.1

###
# modificará el registro a partir de los parámetros enviados en el PUT y 
# devolverá el id del registro modificado y sus datos
PUT http://localhost:5000/f_restfull/api/recipes/5f7b4b6204799f5cf837b1e1 HTTP/1.1
Content-Type: application/json

{
    "name":"Cubatillapara3",
    "ingredients":[{"name":"Coke","quantity":{"unit":"ml","amount":40}}],
    "instructions":["Shake the cup and shout very loud!!."],
    "slug":"cubatillapara3"
}

###
# Borrará el registro correspondiente y devolverá el id del registro borrado
DELETE http://localhost:5000/f_restfull/api/recipes/5f7daa018ec9dfb536781afa HTTP/1.1
